/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CostEstimatorRouteImport } from './routes/cost-estimator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DefectsRouteImport } from './routes/defects'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportsRouteImport } from './routes/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostEstimatorRoute = CostEstimatorRouteImport.update({
  id: '/cost-estimator',
  path: '/cost-estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsRoute = DefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cost-estimator': typeof CostEstimatorRoute
  '/dashboard': typeof DashboardRoute
  '/defects': typeof DefectsRoute
  '/inspections': typeof InspectionsRoute
  '/live': typeof LiveRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cost-estimator': typeof CostEstimatorRoute
  '/dashboard': typeof DashboardRoute
  '/defects': typeof DefectsRoute
  '/inspections': typeof InspectionsRoute
  '/live': typeof LiveRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cost-estimator': typeof CostEstimatorRoute
  '/dashboard': typeof DashboardRoute
  '/defects': typeof DefectsRoute
  '/inspections': typeof InspectionsRoute
  '/live': typeof LiveRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cost-estimator'
    | '/dashboard'
    | '/defects'
    | '/inspections'
    | '/live'
    | '/map'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cost-estimator'
    | '/dashboard'
    | '/defects'
    | '/inspections'
    | '/live'
    | '/map'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/cost-estimator'
    | '/dashboard'
    | '/defects'
    | '/inspections'
    | '/live'
    | '/map'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostEstimatorRoute: typeof CostEstimatorRoute
  DashboardRoute: typeof DashboardRoute
  DefectsRoute: typeof DefectsRoute
  InspectionsRoute: typeof InspectionsRoute
  LiveRoute: typeof LiveRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-estimator': {
      id: '/cost-estimator'
      path: '/cost-estimator'
      fullPath: '/cost-estimator'
      preLoaderRoute: typeof CostEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects': {
      id: '/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof DefectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostEstimatorRoute: CostEstimatorRoute,
  DashboardRoute: DashboardRoute,
  DefectsRoute: DefectsRoute,
  InspectionsRoute: InspectionsRoute,
  LiveRoute: LiveRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
